# NOTE:  EVERY setting must appear in this file.  Items not appearing
# in this file will be deleted from the settings.yml file when
# update_cyber_indicators is run.
production:
  STIX_PREFIX: NCCIC
  SSO_AD: true
  SYSTEM_GUID: <RETAIN>
  DEFAULT_MAX_RECORDS: 100
  MAX_PER_PAGE: 100
  TOU: true
  MODE: CIR
  HUMAN_REVIEW_CLEAR_TO: PII Redacted
  HUMAN_REVIEW_ENABLED: false
  SANITIZATION_ENABLED: false
  CISCP_ID_PATTERNS:
    CISCP_TITLE: ['\A(?:(?:MAR|MIFR|JIB|JAR)-.*|(?:IB|AR)-\d{2}-[12]0\d{3})']
    CISCP_TLP_COLOR: ['\A(?:WHITE|GREEN|AMBER)\Z']
  CLASSIFICATION: false
  BANNER_TEXT: UNCLASSIFIED
  BANNER_TEXT_COLOR: FFFFFF
  BANNER_COLOR: 00FF00
  READ_ONLY_EXT: -dup
  USE_AMQP_SENDER: false
  USE_AMQP_RECEIVER: false
  USE_AMQP_RECEIVER_MESSAGE_PROCESSOR: false
  AMQP_MAX_XML_MESSAGE_PROCESSORS: 5
  AMQP_MAX_JSON_MESSAGE_PROCESSORS: 5
  FLARE_IN_REPL_TYPE: flare_in
  FLARE_OUT_REPL_TYPE: flare_out
  XML_PARSING_LIBRARY: nokogiri
  DATABASE_POOL_LOGGING_ENABLED: false
  DATABASE_POOL_STATS_UPDATE_FREQUENCY: 30
  DATABASE_POOL_ENSURE_THREAD_CONNECTION_CLEARING: true
  DATABASE_POOL_LOGGING_ON_THREAD_ENTRY_ENABLED: false
  DATABASE_POOL_LOGGING_ON_THREAD_EXIT_ENABLED: false
  SOLR_INDEX_FREQUENCY_IN_SECONDS: 60
  PENDING_MARKING_FREQUENCY_IN_SECONDS: 0
  DISSEMINATION_QUEUE_PROCESSOR_FREQUENCY_IN_MINUTES: 0
  DISSEMINATION_LABELING_ENABLED: false
  DISSEMINATION_TRANSFORMING_ENABLED: false
  SEND_FLARE_IDS: parent
  CONCURRENT_LOGINS: 3
  AIS_PROVIDER:
  FLARE_AVP_PATH:
