Rails.application.config.assets.precompile += %w( ie9.css )
Rails.application.config.assets.precompile += %w( ie8.js )
Rails.application.config.assets.precompile += %w( ace/font-awesome.css )
Rails.application.config.assets.precompile += %w( ace/bootstrap.css )
Rails.application.config.assets.precompile += %w( ace/ace.css )
Rails.application.config.assets.precompile += %w( ace/ace-fonts.css )

Rails.application.config.assets.precompile += %w( ace/fontawesome-webfont.eot )
Rails.application.config.assets.precompile += %w( ace/fontawesome-webfont.woff )
Rails.application.config.assets.precompile += %w( ace/fontawesome-webfont.ttf )
Rails.application.config.assets.precompile += %w( ace/fontawesome-webfont.svg )
Rails.application.config.assets.precompile += %w( ace/DXI1ORHCpsQm3Vp6mXoaTXhCUOGz7vYGh680lGh-uXM.woff )
Rails.application.config.assets.precompile += %w( ace/cJZKeOuBrn4kERxqtaUH3T8E0i7KZn-EPnyo3HZu7kw.woff )
Rails.application.config.assets.precompile += %w( jquery-ui.min.js )
