#!/bin/bash
echo "Setting authentication mode to kerberos..."
/var/apps/cyber-indicators/bin/initialize-system-settings
/var/apps/cyber-indicators/bin/initialize-application-webserver-with-kerberos
BASIC=false TEMPLATE=/etc/cyber-indicators/templates/etc/cyber-indicators/config/authenticators.yml.erb OUTFILE=/etc/cyber-indicators/config/authenticators.yml /var/apps/cyber-indicators/bin/rake db:template:create

