# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffea14e7df8b9daf3ac80c282a2383b021a307a14d5d991f7cd7f289432397ad1746bfc0897688d593205c6d56342fdea6befa4bf7190d2efec7405b016acb7e

test:
  secret_key_base: d9464eb3e815d68634d2bdbf46e85e5e8d213458dadd05ddc96fdba10747d06bf16839975c40670c575ea51ec5aa2c0358d91e59aab70362234cfe6574a03f33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= if defined?($servlet_context) then $servlet_context.getInitParameter("rails.config.secret.key") else ENV['SECRET_KEY_BASE'] end %>
