#!/bin/bash

# Loads a WeatherMap heatmap image via the API using a curl script. Demonstrates
# that the API heatmap upload is functional. Note that ONLY a mchine user can
# do database updates like this.

API_KEY="7a3c834c1f07d46f2384b52df686fb24de499bff14c48112750b0d55c7b7e126"

API_KEY_HASH="19e032ab08a75345ebb3b672e4aaf764ace744153ae2e04f150581a946b27d05"

curl -v -k -X POST -H "Content-type: image/png" -H "api_key: ${API_KEY}" -H "api_key_hash: ${API_KEY_HASH}" --data-binary "@test_heatmap_upload.png" "https://127.0.0.1:3000/cyber-indicators/heatmaps?organization_token=USA.DHS.US-CERT&async=true"
