# The table stores mappings between the "before_id" received from an external
# data provider and the sanitized "after_id" generated by DHS.

class CreateIdMappings < ActiveRecord::Migration

  def change
    create_table :id_mappings do |t|
      t.string :before_id
      t.string :after_id
      t.timestamps null: false
    end

    add_index :id_mappings, :before_id
  end

end
